### ISSUE TITLE
How to support Angular4

### ISSUE THREAD

**Issue by jiangyh1024** [intbot/ng2-pdfjs-viewer#11]
My angular version is 4.4.7. When starting the project, the error throws:

ERROR in Metadata version mismatch for module C:/software/project/lazy/node_modules/ng2-pdfjs-viewer/ng2-pdfjs-viewer.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/software/project/lazy/src/app/app.module.ts, resolving symbol AppModule in C:/software/project/lazy/src/app/app.module.ts

it seems the Metadata version should be 3 instead of 4, how to fix this issue ? Please help, thanks

**Comment by codehippie1** [comment]
@jiangyh1024 Can you provide a simple working version where I can reproduce this issue

**Comment by adecass** [comment]
I'm having the same issue using Angular 4...  Is this resolved?


ERROR in Error: Metadata version mismatch for module ng2-pdfjs-viewer/ng2-pdfjs-viewer.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (node_modules\@angular\compiler\bundles\compiler.umd.js:25586:34)
    at StaticSymbolResolver._createSymbolsOf (node_modules\@angular\compiler\bundles\compiler.umd.js:25374:46)
    at StaticSymbolResolver.getSymbolsOf (node_modules\@angular\compiler\bundles\compiler.umd.js:25355:14)
    at \node_modules\@angular\compiler\bundles\compiler.umd.js:24214:30
    at Array.forEach (<anonymous>)
    at extractProgramSymbols (node_modules\@angular\compiler\bundles\compiler.umd.js:24213:79)
    at AotCompiler.analyzeModulesAsync (\node_modules\@angular\compiler\bundles\compiler.umd.js:23771:47)
    at CodeGenerator.codegen (\node_modules\@angular\compiler-cli\src\codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (\node_modules\@angular\compiler-cli\src\ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (\node_modules\@ngtools\webpack\src\plugin.js:391:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by adecass** [comment]
Here's the package.json for a new Angular 4 project.  However, the outcome hasn't changed. 
**ERROR in Error: Metadata version mismatch for module ng2-pdfjs-viewer/ng2-pdfjs-viewer.d.ts, found version 4, expected 3**

{
  "name": "ng4-slow-build",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "core-js": "^2.4.1",
    "ng2-pdfjs-viewer": "^0.2.29",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.10",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.3.3"
  }
}

**Comment by codehippie1** [comment]
Closing this issue of no activity. Use the latest package(Upgraded to angular 7) and if this issue still exists, let me know.

**Comment by ihorbond** [comment]
@codehippie1 Hi I have just come across the same issue running Angular 4. I tried to replicate on [stackblitz ](https://stackblitz.com/edit/angular-ftyqpe) and while I can't see the build error as I do when I run ng build in my console it doesn't seem to work. Do you know what could be wrong ?

**Comment by codehippie1** [comment]
I tried to access the stackblits link you provided and got a message, "Yikes! The page you requested couldn't be found."

**Comment by avssolutions** [comment]
I have the same issues still?

**Comment by VictorCoddistudio** [comment]
Hi @codehippie1 :) 
I'm using the last version (5.0.5) with angular 4.

![image](https://user-images.githubusercontent.com/26631589/74051479-a713b080-499d-11ea-9d48-f7bfbdec45f9.png)

But it seems the npm install is downloading the package with a wrong metadata info for angular 4.

![image](https://user-images.githubusercontent.com/26631589/74051601-e6da9800-499d-11ea-8e73-9109a57e0751.png)

And I need to change the version from 4 to 3 on the metadata.json file, in order to start (npm start) my angular 4 application.

Do you know about a non-tricky solution to this?

**Comment by ihorbond** [comment]
> Hi @codehippie1 :)
> I'm using the last version (5.0.5) with angular 4.
> 
> ![image](https://user-images.githubusercontent.com/26631589/74051479-a713b080-499d-11ea-9d48-f7bfbdec45f9.png)
> 
> But it seems the npm install is downloading the package with a wrong metadata info for angular 4.
> 
> ![image](https://user-images.githubusercontent.com/26631589/74051601-e6da9800-499d-11ea-8e73-9109a57e0751.png)
> 
> And I need to change the version from 4 to 3 on the metadata.json file, in order to start (npm start) my angular 4 application.
> 
> Do you know about a non-tricky solution to this?

For angular 4 use v3.0.8

**Comment by VictorCoddistudio** [comment]
Hi @ihorbond 
The 3.0.8 version was not found.
![image](https://user-images.githubusercontent.com/26631589/74056621-f8c13880-49a7-11ea-9ecf-a26748be5c52.png)

**Comment by ihorbond** [comment]
> Hi @ihorbond
> The 3.0.8 version was not found.
> ![image](https://user-images.githubusercontent.com/26631589/74056621-f8c13880-49a7-11ea-9ecf-a26748be5c52.png)

The package is ng2-pdf-viewer

**Comment by VictorCoddistudio** [comment]
@ihorbond

**Comment by VictorCoddistudio** [comment]
Thanks @ihorbond but I need the ng2-pdfjs-viewer

**Comment by ihorbond** [comment]
> Thanks @ihorbond but I need the ng2-pdfjs-viewer

My bad confused with a different package I ended up using

**Comment by VictorCoddistudio** [comment]
Don't worry @ihorbond ! Thanks anyway :)
