### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'location')

### ISSUE THREAD

**Issue by Gramli** [intbot/ng2-pdfjs-viewer#259]
Hi, 

we recently updated to "ng2-pdfjs-viewer" version "18.0.0". After this update, we started encountering an error. The first time we open a PDF file, it works correctly, but when we open the same file again, it starts throwing an exception. However, it eventually displays the PDF properly.

```
document-viewer.component.ts:18 TypeError: Cannot read properties of null (reading 'location')
    at PdfJsViewerComponent.loadPdf (ng2-pdfjs-viewer.mjs:298:53)
    at PdfJsViewerComponent.refresh (ng2-pdfjs-viewer.mjs:127:14)
    at Object.next (document-viewer.component.ts:16:26)
    at ConsumerObserver.next (Subscriber.js:91:33)
    at SafeSubscriber._next (Subscriber.js:60:26)
    at SafeSubscriber.next (Subscriber.js:31:18)
    at Subject.js:34:30
    at errorContext (errorContext.js:19:9)
    at Subject.next (Subject.js:27:21)
```

Every time we open pdf file again, number of exception raise up:
![image](https://github.com/user-attachments/assets/2ddc0234-4eda-43e2-a7f9-c59035040837)

After we refresh the page with F5, the first opening of the file is again without errors.

In the previous version, it was OK. Is anyone else encountering this issue too?

**Usage:**

```html
<div style="width: 100%; height: 100%; min-height: 750px">
  <ng2-pdfjs-viewer #pdfViewer></ng2-pdfjs-viewer>
</div>

```

```ts
  @ViewChild('pdfViewer', { static: true }) pdfViewer: any;

  @Input() set document(value: Observable<Blob>) {
    if (this.pdfViewer && value) {
      value.subscribe((response) => {
        try {
          this.pdfViewer.pdfSrc = response;
          this.pdfViewer.refresh();
        } catch (error) {
          console.error(error);
        }
      });
    }
  }
```

**Comment by aoihikari** [comment]
I am getting the same issue too. If this is not fixed soon, I will have to revert my upgrade and go back to the previous version. Does anyone know if the previous version is compatible with Angular 18?

**Comment by enorfelt** [comment]
Yes seeing the same issue here.

**Comment by codehippie1** [comment]
@NextNebula @enorfelt @aoihikari @Gramli 

These are merged and released some time back. Also, I have upgraded the library to PDF.js 5.x in the latest release of v25.x. 

Full documentation and live-demo can be found here - https://angular-pdf-viewer-docs.vercel.app/
